apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: med-erp-backend
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/uma-kamuni/edublitz-b2b-medical-erp.git
    targetRevision: dev
    path: k8s
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: med-erp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true